# Generated by Django 2.2.1 on 2019-05-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='professores',
            new_name='usuarios',
        ),
    ]
