# Generated by Django 2.2.1 on 2019-05-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alunos',
            new_name='curso',
        ),
    ]
