# Generated by Django 2.2.1 on 2019-05-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='discipilna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomediscipilna', models.CharField(max_length=90, verbose_name='nomediscipilna')),
                ('descriçãodis', models.CharField(max_length=1000, verbose_name='descrição')),
            ],
        ),
    ]
